version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: development_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: kfx123456
      MONGO_INITDB_DATABASE: development_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: