service: serverless-project-name

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

custom:
  basePath:
    dev: dev
    uat: uat
    prod: ""

functions:
  getUserByEmail:
    handler: src/interfaces/getUserByEmail.handler
    description: Get user by email
    events:
      - http:
          path: /users/find-user/{email}
          method: get
          cors: true

  registerUser:
    handler: src/interfaces/registerUser.handler
    description: Register new user manually
    events:
      - http:
          path: /users/register
          method: post
          cors: true


plugins:
  - serverless-offline

resources:
  Resources:
    HttpApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ${self:service}-${self:provider.stage}
        ProtocolType: HTTP
        CorsConfiguration:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS

  Outputs:
    HttpApiUrl:
      Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${self:custom.basePath.${self:provider.stage}}"